services:
  - type: static
    name: tsunamiflow-static
    branch: main
    publishPath: . # replace with the folder where your index.html lives
    routes:
      - path: /*
        headers:
          Access-Control-Allow-Origin: "https://tsunamiflow.club"
          Cache-Control: "public, max-age=86400"
      - path: /Music/*
        rewrite: https://radio.tsunamiflow.club/Music/:splat
        headers:
          Access-Control-Allow-Origin: "https://tsunamiflow.club"
          Cache-Control: "public, max-age=86400"